spring:
        profiles:
                  active: dev
        jpa:
             open-in-view: true
             properties:
                         hibernate:
                                    cache:
                                          use_second_level_cache: true
                                          use_query_cache: true
                                          region:
                                                  factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
                                          hazelcast:
                                                     instance_name: ${spring.hazelcast.instance-name}
        datasource:
                    max-wait: 10000
                    max-active: 5
                    test-on-borrow: true
        dbunit:
                operationType: CLEAN_INSERT
                sample-file: src/test/resources/sample-data.xml
        hazelcast:
                    group:
                           name: ${random.uuid}
                           password: dev-pass
                    management:
                               enabled: false
                               url: http://localhost:8080/mancenter
                    network:
                             interfaces:
                                          enabled: false
                                          interface: 192.168.199.*
                    instance-name: spring-shiro-hibernate-cache
                    session:
                             timeout: 1800
                    heartbeat:
                              seconds: 5
        jackson:
                  serialization:
                                  write_dates_as_timestamps: true
db:
   name: appsugar_kotlin
server:
        compression:
                     enabled: true
                     mime-types: application/json,application/xml,text/html,text/xml,text/plain
shiro:
      cipher:
             key: u39fskcJooyWj2jA6Vs2lA==
      session:
             name: appsession

---
spring:
      profiles: dev
      datasource:
                  url: jdbc:h2:~/tmp/${db.name}
                  username: sa
                  password:
                  driver-class-name: org.h2.Driver
      dbunit:
             data-factory: org.dbunit.ext.h2.H2DataTypeFactory
      jpa:
          show-sql: true
          hibernate:
                      ddl-auto: none
---
spring:
      profiles: dev_mysql
      datasource:
                  url: jdbc:mysql://localhost:3306/${db.name}?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8
                  username: root
                  password: 123456
                  driver-class-name: com.mysql.jdbc.Driver
      jpa:
          hibernate:
                     ddl-auto: update
      dbunit:
              data-factory: org.dbunit.ext.mysql.MySqlDataTypeFactory