spring:
  application:
    name: appsugar-web
  data:
    redis:
      repositories:
        enabled: false
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 8
  jpa:
    open-in-view: true
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    max-wait: 10000
    max-active: 1
    test-on-borrow: true
    url: jdbc:h2:~/tmp/${db.name}
    username: sa
    password:
    driver-class-name: org.h2.Driver
  dbunit:
    operationType: CLEAN_INSERT
    sample-file: src/test/resources/sample-data.xml
    data-factory: org.dbunit.ext.h2.H2DataTypeFactory
  jackson:
    serialization:
      write_dates_as_timestamps: true
    default-property-inclusion: NON_NULL
  security:
    user:
      name: changeme
      password: changeme
db:
  name: appsugar_kotlin
server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
transporter: nettyNF
dubbo:
  protocol:
    name: dubbo
    port: 20880
    dispatcher: direct
    transporter: ${transporter}
  provider:
    transporter: ${transporter}
  consumer:
    client: ${transporter}
  registry:
    address: multicast://224.5.6.7:1234
    transporter: ${transporter}

---
spring:
  profiles: mysql
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:~/tmp/${db.name}
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  dbunit:
    data-factory: org.converters.dialect.MySQL5InnoDBDialect