spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:~/tmp/${db.name}
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  dbunit:
    data-factory: org.converters.dialect.MySQL5InnoDBDialect