spring:
  application.name: archetypes
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        #default enabled in hibernate 5
        batch_versioned_data: true
        jdbc:
          #config this when use oracle (default is 10)
          fetch_size: 10000
          batch_size: 10000
  datasource:
    hikari:
      max-lifetime: 1800000
      idle-timeout: 60000
      minimum-idle: 0
      maximum-pool-size: 17
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:appsugar
      username: sa
      password:
  jackson:
    serialization:
      write_dates_as_timestamps: true
  #开放spring自身jmx
  jmx:
    enabled: true
#config logging
logging:
  file:
    #正式环境需要映射 -Dlogging.file.name=xxx 解决spring cloud环境初始化日志跟当前环境不一致问题
    #这里配置主要是为了解决 spring boot admin 管理系统查看日志问题
    name: ./build/logs/app.log
  level:
    org.appsugar: DEBUG
    org.springframework.web.servlet.mvc.method.annotation: ERROR
    ROOT: WARN

server:
  tomcat:
    threads:
      max: 17
      min-spare: 1
  port: 80
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

#开放所有exposure,在生产不允许暴露server.port以外的端口
management:
  security:
    #在启动命令行里生成随机数来限制账号密码的改变
    username: xxxx
    password: xxxx
  endpoints.web:
    exposure.include: "*"
  #makesure do not exposed all port to the internet
  security.enabled: false
  server.port: 0
  endpoint:
    logfile:
      external-file: ${logging.file.name}
    shutdown:
      enabled: true
    env:
      post:
        enabled: true
#在微服务方式下, 使用被动发现.
spring.boot.admin.client:
  enabled: true
  url: http://localhost:8081/
  username: admin
  password: admin
  instance:
    prefer-ip: true
    metadata:
      user:
        name: ${management.security.username}
        password: ${management.security.username}