spring:
  application.name: archetypes
  jpa:
    open-in-view: true
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    max-wait: 10000
    max-active: 5
    test-on-borrow: true
    url: jdbc:h2:~/tmp/${db.name}
    username: sa
    password:
    driver-class-name: org.h2.Driver
  dbunit:
    operationType: CLEAN_INSERT
    sample-file: src/test/resources/sample-data.xml
    data-factory: org.dbunit.ext.h2.H2DataTypeFactory
  jackson:
    serialization:
      write_dates_as_timestamps: true
  #开放spring自身jmx
  jmx:
    enabled: true
#config logging
logging:
  file:
    #正式环境需要映射 -Dlogging.file.name=xxx 解决spring cloud环境初始化日志跟当前环境不一致问题
    #这里配置主要是为了解决 spring boot admin 管理系统查看日志问题
    name: ./build/logs/app.log
  level:
    org.appsugar: DEBUG
server:
  port: 80
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

#开放所有exposure,在生产不允许暴露server.port以外的端口
management:
  endpoints.web:
    exposure.include: "*"
    base-path: /att
  security.enabled: false
  server.port: 0
  endpoint:
    env:
      post:
        enabled: true
spring.boot.admin.client:
  enabled: true
  url: http://localhost:8081/
  username: admin
  password: admin
---
spring:
  profiles: mysql
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:~/tmp/${db.name}
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  dbunit:
    data-factory: org.converters.dialect.MySQL5InnoDBDialect