spring:
  application:
    name: appsugar-web
  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:~/tmp/${db.name}
    username: sa
    password:
    #driver-class-name: org.h2.Driver
    hikari:
      maxPoolSize: 1
      minIdle: 0
  dbunit:
    operationType: CLEAN_INSERT
    sample-file: src/test/resources/sample-data.xml
    data-factory: org.dbunit.ext.h2.H2DataTypeFactory
  jackson:
    serialization:
      write_dates_as_timestamps: true
    default-property-inclusion: NON_NULL
  security:
    user:
      name: ${random.uuid}
      password: ${random.uuid}
  task:
    execution:
      pool:
        core-size: 1
        keep-alive: 60s
        max-size: 50
db:
  name: appsugar_kotlin
server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
spring.boot.admin.client:
  enabled: false
  url: http://your-spring-boot-admin-server-domain/
  user:
    name: xxx
    password: xxx
  instance:
    metadata:
      user:
        name: ${spring.security.user.name}
        password: ${spring.security.user.password}
---
spring:
  profiles: mysql
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost/${db.name}?createDatabaseIfNotExist=true&useSSL=false&characterEncoding=utf-8&rewriteBatchedStatements=true
    username: root
    password: 123456
    hikari:
      maxPoolSize: 200
    #driver-class-name: com.mysql.jdbc.Driver
  dbunit:
    data-factory: org.converters.dialect.MySQL5InnoDBDialect