spring:
        datasource:
                     url: jdbc:h2:~/tmp/${db.name}
                     username: sa
                     password:
                     driver-class-name: org.h2.Driver
        dbunit:
                data-factory: org.dbunit.ext.h2.H2DataTypeFactory
        jpa:
            show-sql: true